/*
 * FiltroDialog.java
 *
 * Created on 24 mai 2007, 20:37
 */

package org.ai.pattern.gui;


import java.awt.GridLayout;
import javax.swing.JTextField;

/**
 *
 * @author  yannart
 */
public class FiltroDialog extends javax.swing.JDialog {
    private JTextField [] elementosmatriz;
    private MainFrame parent;
    
    
    /** Creates new form FiltroDialog */
    public FiltroDialog(MainFrame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTamano = new javax.swing.JPanel();
        jComboBoxTamano = new javax.swing.JComboBox();
        jPanelMatriz = new javax.swing.JPanel();
        jPanelMatrizData = new javax.swing.JPanel();
        jPanelPredeterminados = new javax.swing.JPanel();
        jComboBoxPredeterminados = new javax.swing.JComboBox();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelTamano.setBorder(javax.swing.BorderFactory.createTitledBorder("Tamano matriz"));

        jComboBoxTamano.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3 * 3", "5 * 5" }));

        javax.swing.GroupLayout jPanelTamanoLayout = new javax.swing.GroupLayout(jPanelTamano);
        jPanelTamano.setLayout(jPanelTamanoLayout);
        jPanelTamanoLayout.setHorizontalGroup(
            jPanelTamanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTamanoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxTamano, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelTamanoLayout.setVerticalGroup(
            jPanelTamanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTamanoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxTamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanelMatriz.setBorder(javax.swing.BorderFactory.createTitledBorder("Matriz"));

        jPanelMatrizData.setBackground(new java.awt.Color(204, 255, 102));
        jPanelMatrizData.setLayout(new java.awt.GridLayout(3, 3));

        javax.swing.GroupLayout jPanelMatrizLayout = new javax.swing.GroupLayout(jPanelMatriz);
        jPanelMatriz.setLayout(jPanelMatrizLayout);
        jPanelMatrizLayout.setHorizontalGroup(
            jPanelMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMatrizLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMatrizData, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelMatrizLayout.setVerticalGroup(
            jPanelMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMatrizLayout.createSequentialGroup()
                .addComponent(jPanelMatrizData, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelPredeterminados.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros predeterminados"));

        jComboBoxPredeterminados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "paso alto", "paso bajo" }));

        javax.swing.GroupLayout jPanelPredeterminadosLayout = new javax.swing.GroupLayout(jPanelPredeterminados);
        jPanelPredeterminados.setLayout(jPanelPredeterminadosLayout);
        jPanelPredeterminadosLayout.setHorizontalGroup(
            jPanelPredeterminadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPredeterminadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxPredeterminados, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelPredeterminadosLayout.setVerticalGroup(
            jPanelPredeterminadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPredeterminadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxPredeterminados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jButtonAceptar.setText("Aplicar");

        jButtonCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAceptar)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonCancelar))
                    .addComponent(jPanelTamano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPredeterminados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAceptar, jButtonCancelar});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanelPredeterminados, jPanelTamano});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelTamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelPredeterminados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCancelar)
                            .addComponent(jButtonAceptar))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonAceptar, jButtonCancelar});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanelPredeterminados, jPanelTamano});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void initMyComponents(){
        /*GridLayout layout = new GridLayout();
        layout.setColumns(3);
        layout.setRows(3);
        jPanelMatrizData.setLayout(layout);*/
        
        elementosmatriz = new JTextField[25];
        for(int i = 0; i < elementosmatriz.length; i++){
            elementosmatriz[i] = new JTextField();
            elementosmatriz[i].setHorizontalAlignment(JTextField.CENTER);
            jPanelMatrizData.add(elementosmatriz[i]);
        }
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox jComboBoxPredeterminados;
    private javax.swing.JComboBox jComboBoxTamano;
    private javax.swing.JPanel jPanelMatriz;
    private javax.swing.JPanel jPanelMatrizData;
    private javax.swing.JPanel jPanelPredeterminados;
    private javax.swing.JPanel jPanelTamano;
    // End of variables declaration//GEN-END:variables
    
}
