/*
 * ImageFrame.java
 *
 * Created on 9 mai 2007, 21:35
 */

package org.ai.pattern.gui;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.JPanel;
import org.ai.pattern.ImageLoader;

/**
 *
 * @author  yannart
 */
public class ImageFrame extends javax.swing.JInternalFrame {
    
    /** Creates new form ImageFrame
     * @param file
     */
    public ImageFrame(File file) {
        initComponents();
        this.setTitle(file.getName());
        
        BufferedImage image = ImageLoader.loadImage(file);
        jScrollPaneContenedor.setViewportView(new ImagePanel(image));
        try {
            this.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {}
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneContenedor = new javax.swing.JScrollPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen.png"))); // NOI18N
        setVisible(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPaneContenedor;
    // End of variables declaration//GEN-END:variables
    
}

/**
 */
class ImagePanel extends JPanel{
    private BufferedImage image;
    
    /**
     * @param image Imagen contenida en el panel
     */
    public ImagePanel(BufferedImage image){
        this.image = image;
        Dimension dimension = new Dimension(image.getWidth(), image.getHeight());
        this.setPreferredSize(dimension);
        this.setSize(dimension);
    }
    
    /**
     * @return Imagen contenida en el panel
     */
    public BufferedImage getImage(){
        return image;
    }
    
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        if(image != null)
            g.drawImage(image, 0, 0, image.getWidth(), image.getHeight(), this);
    }
}
